#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = new Symfony\Component\Console\Application(
  'Tagmeo', $app::version()
);

$kernel->addCommands([
  new Tagmeo\Console\Commands\SetupCommand(),
  new Tagmeo\Console\Commands\ServeCommand()
]);

$kernel->run();
